openapi: 3.0.0
info:
  title: "week-10-mnajmytsss"
  version: 1.0.0
  description: "RESTful API with expressjs, nodejs, and swagger"
servers:
  - url: http://localhost:3000
    description: "Development server"
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Bearer with JWT Token"
  schemas:
    RegisterUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          minLength: 8
        role:
          type: string
      required:
        - username
    LoginUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    BadRequest:
      type: object
      properties:
        error:
          type: string
paths:
  /auth/register:
    post:
      summary: "Register new user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUser"
      responses:
        "200":
          description: "User Created"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      role:
                        type: string
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /auth/login:
    post:
      summary: "Login user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUser"
      responses:
        "200":
          description: "Login Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: string
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /v1/transfers:
    post:
      security:
        - bearer: []
      summary: "create transfers"
      responses:
        "200":
          description: "create transfers"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        amount:
                          type: integer
                        currency:
                          type: string
                        sourceAccount:
                          type: string
                        destinationAccount:
                          type: string
                        status:
                          type: string
  /s/v1/transfers:
    get:
      security:
        - bearer: []
      summary: "Get all transfers"
      responses:
        "200":
          description: "Get all transfers"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        amount:
                          type: integer
                        currency:
                          type: string
                        sourceAccount:
                          type: string
                        destinationAccount:
                          type: string
                        status:
                          type: string
  /v1/transfers/:id:
    patch:
      security:
        - bearer: []
      summary: "patch transfers status"
      responses:
        "200":
          description: "patch transfers status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: string
