info:
  _postman_id: 35a5dc17-d985-4a75-bd79-00a1714283f1
  name: week-10-mnajmytsss
  schema: https://schema.getpostman.com/json/collection/v2.1.0/collection.json
  _exporter_id: '29017989'
item:
  - name: auth
    item:
      - name: register
        request:
          method: POST
          header: []
          body:
            mode: raw
            raw: |-
              {
                  "username": "nutsme",
                  "password": "nutsme123",
                  "role": "maker"
              }
            options:
              raw:
                language: json
          url:
            raw: http://localhost:3000/auth/register
            protocol: http
            host:
              - localhost
            port: '3000'
            path:
              - auth
              - register
        response: []
      - name: login
        request:
          method: GET
          header: []
        response: []
  - name: post transfer
    request:
      method: POST
      header: []
      body:
        mode: raw
        raw: |-
          {
              "amount": "20000",
              "currency": "IDR",
              "sourceAccount": "64e5d2f96595d91d0ad556e6",
              "destinationAccount": "64e5ce99eecf16353371fbdd" 
          }
        options:
          raw:
            language: json
      url:
        raw: http://localhost:3000/v1/transfers
        protocol: http
        host:
          - localhost
        port: '3000'
        path:
          - v1
          - transfers
    response: []
  - name: get all transfers
    request:
      method: GET
      header: []
      url:
        raw: http://localhost:3000/v1/transfers
        protocol: http
        host:
          - localhost
        port: '3000'
        path:
          - v1
          - transfers
    response: []
  - name: put transfer
    request:
      method: PUT
      header: []
      body:
        mode: raw
        raw: |-
          {
                      "amount": "23000",
                      "currency": "IDR",
                      "sourceAccount": "64e5ce99eecf16353371fbdd",
                      "destinationAccount": "64e5d2f96595d91d0ad556e6",
                      "status": "pending"
                  }
        options:
          raw:
            language: json
      url:
        raw: http://localhost:3000/v1/transfers/64e5d6a16595d91d0ad556e9
        protocol: http
        host:
          - localhost
        port: '3000'
        path:
          - v1
          - transfers
          - 64e5d6a16595d91d0ad556e9
    response: []
  - name: patch status transfer
    request:
      method: PATCH
      header: []
      body:
        mode: raw
        raw: |-
          {
                      "amount": "33000",
                      "currency": "IDR",
                      "sourceAccount": "64e5ce99eecf16353371fbdd",
                      "destinationAccount": "64e5d2f96595d91d0ad556e6",
                      "status": "accepted"
                  }
        options:
          raw:
            language: json
      url:
        raw: http://localhost:3000/v1/transfers/64e5d6a16595d91d0ad556e9
        protocol: http
        host:
          - localhost
        port: '3000'
        path:
          - v1
          - transfers
          - 64e5d6a16595d91d0ad556e9
    response: []
  - name: delete transfer
    request:
      method: DELETE
      header: []
      url:
        raw: http://localhost:3000/v1/transfers/64e5e0931015807c13c3daa9
        protocol: http
        host:
          - localhost
        port: '3000'
        path:
          - v1
          - transfers
          - 64e5e0931015807c13c3daa9
    response: []
